services:
  - type: web
    name: qoricash
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py run:app
    preDeployCommand: bash migrate.sh
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
