services:
  - type: web
    name: qoricash
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
